name: Publish to TestPyPI

on:
  push:
    branches: [ main ]
    paths:
      - 'pyproject.toml'
      - 'src/**'
      - 'stock_recommender.py'
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine pytest
        pip install -r requirements.txt

    - name: Run quick tests
      run: |
        python -m pytest tests/ -x -v --tb=short

    - name: Build package
      run: python -m build

    - name: Check package
      run: |
        python -m twine check dist/*
        ls -la dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true
